"""Constants for the Off-delay integration tests."""

from custom_components.offdelay.const import (
    CONF_CLIMATE_DAY_START_HOUR,
    CONF_CLIMATE_NIGHT_START_HOUR,
    CONF_CLIMATES_BOOST,
    CONF_GUEST_TURN_OFF_DELAY,
    CONF_GUEST_TURN_ON_DELAY,
    CONF_OCCUPANCY_SENSORS,
    CONF_PERSONS,
    CONF_SUMMER_DAY_MIN_TEMP,
    CONF_SUMMER_NIGHT_MAX_TEMP,
    CONF_SUMMER_NIGHT_MIN_TEMP,
    CONF_SUMMER_NIGHT_TEMP_SENSOR,
    CONF_WINTER_DAY_MAX_TEMP,
    CONF_WINTER_NIGHT_MAX_TEMP,
    CONF_WINTER_NIGHT_MIN_TEMP,
    CONF_WINTER_NIGHT_TEMP_SENSOR,
)

MOCK_CONFIG = {
    CONF_WINTER_DAY_MAX_TEMP: 15.0,
    CONF_SUMMER_DAY_MIN_TEMP: 20.0,
    CONF_CLIMATE_DAY_START_HOUR: 8,
    CONF_CLIMATE_NIGHT_START_HOUR: 17,
    CONF_GUEST_TURN_ON_DELAY: 5,
    CONF_GUEST_TURN_OFF_DELAY: 15,
}

MOCK_CONFIG_WITH_NIGHT_SENSORS = {
    CONF_WINTER_DAY_MAX_TEMP: 15.0,
    CONF_SUMMER_DAY_MIN_TEMP: 20.0,
    CONF_SUMMER_NIGHT_TEMP_SENSOR: ["sensor.summer_night_temp"],
    CONF_SUMMER_NIGHT_MAX_TEMP: 20.0,
    CONF_SUMMER_NIGHT_MIN_TEMP: 20.0,
    CONF_WINTER_NIGHT_TEMP_SENSOR: ["sensor.winter_night_temp"],
    CONF_WINTER_NIGHT_MAX_TEMP: 20.0,
    CONF_WINTER_NIGHT_MIN_TEMP: 20.0,
    CONF_CLIMATE_DAY_START_HOUR: 8,
    CONF_CLIMATE_NIGHT_START_HOUR: 17,
    CONF_GUEST_TURN_ON_DELAY: 5,
    CONF_GUEST_TURN_OFF_DELAY: 15,
}

MOCK_CONFIG_WITH_OCCUPANCY = {
    CONF_WINTER_DAY_MAX_TEMP: 15.0,
    CONF_SUMMER_DAY_MIN_TEMP: 20.0,
    CONF_CLIMATE_DAY_START_HOUR: 8,
    CONF_CLIMATE_NIGHT_START_HOUR: 17,
    CONF_OCCUPANCY_SENSORS: ["binary_sensor.motion_living_room"],
    CONF_GUEST_TURN_ON_DELAY: 5,
    CONF_GUEST_TURN_OFF_DELAY: 15,
}

MOCK_CONFIG_WITH_PERSONS = {
    CONF_WINTER_DAY_MAX_TEMP: 15.0,
    CONF_SUMMER_DAY_MIN_TEMP: 20.0,
    CONF_CLIMATE_DAY_START_HOUR: 8,
    CONF_CLIMATE_NIGHT_START_HOUR: 17,
    CONF_GUEST_TURN_ON_DELAY: 5,
    CONF_GUEST_TURN_OFF_DELAY: 15,
    CONF_PERSONS: ["person.john", "person.jane"],
}

MOCK_CONFIG_WITH_BOOST_CLIMATES = {
    **MOCK_CONFIG_WITH_NIGHT_SENSORS,
    CONF_CLIMATES_BOOST: [
        "climate.kid_big_bedroom_heatpump",
        "climate.master_bedroom_heatpump",
    ],
}
