#!/usr/bin/env bash
# script/freeze: Freeze pip requirements to requirements.test.txt

set -e

cd "$(dirname "$0")/.."

pip freeze -r requirements.test.txt | \
	sed -n '/##/q;p' > requirements.test.txt.tmp && \
	mv requirements.test.txt.tmp requirements.test.txt
