#!/usr/bin/env bash
# script/unfreeze: Unfreeze pip requirements by removing version pins

set -e

cd "$(dirname "$0")/.."

cat requirements.test.txt | \
	sed 's/==.*//' > requirements.test.txt.tmp && \
	mv requirements.test.txt.tmp requirements.test.txt
